name: shenliyuan
description: 沈理校园 - 校园互助社交应用
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  sqflite: ^2.3.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  photo_manager: ^3.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.4
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  flutter_markdown: ^0.7.6
  webview_flutter: ^4.10.0
  image_cropper: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/scripts/
    - assets/yongzhiyunkao/