org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.daemon.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=true
kotlin.incremental=true
org.gradle.workers.max=2
android.builtInKotlin=false
android.newDsl=false