import {useSearchParams} from 'react-router-dom';
import {useAuth} from './auth';
import {query,rows,time,useApi,write,type Entity} from './api';
import {Empty,Form,QueryState,Stats,useUI,type Field} from './ui';
export const managementTabs:[string,string][]=[['notices','公告'],['sections','版块'],['metrics','AI 指标'],['users','用户'],['releases','版本'],['logs','操作日志']];
const superOnly=new Set(['users','releases','logs']);
const paths:Record<string,string>={notices:'/api/announcements/admin/list',sections:'/api/water/sections',metrics:'/api/admin/ai/metrics',users:'/api/super/users',releases:'/api/super/app-releases',logs:'/api/super/admin_logs'};
export function Management({kind}:{kind:string}){
  const auth=useAuth(),ui=useUI(),[params,setParams]=useSearchParams();
  const allowed=!superOnly.has(kind)||auth.user?.role==='super_admin';
  const q=useApi(allowed?query(paths[kind],{search:params.get('search'),days:kind==='metrics'?7:undefined,page:1,limit:50}):null);
  if(!allowed)return <Empty title="此操作需要超级管理员权限"/>;
  function edit(item?:Entity){ui.open(kind==='notices'?'编辑公告':kind==='sections'?'编辑版块':kind==='users'?'用户管理':'版本管理',kind==='notices'?<NoticeForm item={item}/>:kind==='sections'?<SectionForm item={item!}/>:kind==='users'?<UserForm item={item!}/>:<ReleaseForm item={item}/>)}
  return <><div className="filter-row">{kind==='users'&&<form onSubmit={e=>{e.preventDefault();setParams({tab:kind,search:String(new FormData(e.currentTarget).get('search')||'')})}}><input name="search" aria-label="搜索用户" placeholder="昵称、账号或用户 ID" defaultValue={params.get('search')||''}/><button className="btn">搜索</button></form>}{['notices','releases'].includes(kind)&&<button className="btn primary" onClick={()=>edit()}>新增{kind==='notices'?'公告':'版本草稿'}</button>}<button className="btn" onClick={()=>void q.refetch()}>刷新</button></div><QueryState query={q}>{kind==='metrics'?<Metrics data={q.data||{}}/>:<div className="panel">{rows(q.data,'announcements','sections','users','logs').map(x=><div className="list-row" key={x.id}><div className="list-main"><b>{x.title||x.nickname||x.version_name||x.action||x.name}</b><p>{kind==='logs'?`${x.admin_name} · ${x.target} · ${x.detail}`:kind==='users'?`#${x.id} · ${x.role} · 诚信分 ${x.credit_score}`:kind==='releases'?`${x.version_code} · ${x.status} · ${x.channel}`:x.description||x.status}</p><small>{time(x.created_at)}</small></div>{kind!=='logs'&&<button className="btn" onClick={()=>edit(x)}>管理</button>}</div>)}{!rows(q.data,'announcements','sections','users','logs').length&&<Empty title="暂无记录"/>}</div>}</QueryState></>;
}
function NoticeForm({item={}}:{item?:Entity}){
  const ui=useUI();return <Form fields={[{name:'title',label:'公告标题',value:item.title,required:true},{name:'content',label:'正文',type:'textarea',value:item.content,required:true},{name:'status',label:'状态',value:item.status||'draft',options:[['draft','草稿'],['published','发布'],['archived','归档']]},{name:'display_mode',label:'展示方式',value:item.display_mode||'center',options:[['center','通知中心'],['banner','横幅'],['modal','弹窗']]},{name:'priority',label:'优先级',value:item.priority||'normal',options:[['normal','普通'],['important','重要'],['urgent','紧急']]}]} onSubmit={async(values,form)=>{await write(`/api/announcements${item.id?`/${item.id}`:''}`,{...values,is_pinned:form.get('pinned')==='on',include_new_users:form.get('new_users')==='on'},item.id?'PUT':'POST');await ui.act(async()=>{},'公告已保存');ui.close()}}><label className="check-label"><input name="pinned" type="checkbox" defaultChecked={item.is_pinned}/>置顶</label><label className="check-label"><input name="new_users" type="checkbox" defaultChecked={item.include_new_users}/>新注册用户也可查看</label></Form>;
}
function SectionForm({item}:{item:Entity}){const ui=useUI();return <Form fields={[{name:'title',label:'版块名称',value:item.title,required:true},{name:'subtitle',label:'副标题',value:item.subtitle},{name:'description',label:'版块说明',type:'textarea',value:item.description},{name:'notice_text',label:'版块公告',type:'textarea',value:item.notice_text},{name:'reason',label:'修改原因',required:true}]} onSubmit={async values=>{await write(`/api/water/sections/${encodeURIComponent(item.slug)}`,values,'PATCH');await ui.act(async()=>{},'版块已更新');ui.close()}}/>}
function UserForm({item}:{item:Entity}){const ui=useUI();return <><p>{item.nickname} · #{item.id}</p><p>角色变化会按服务端规则撤销该用户原有令牌。</p><Form fields={[{name:'role',label:'角色',value:item.role,options:[['user','普通用户'],['admin','管理员'],['super_admin','超级管理员']]}]} submit="确认修改角色" onSubmit={async values=>{await write(`/api/super/users/${item.id}/role`,values,'PUT');await ui.act(async()=>{},'角色已更新');ui.close()}}/><Form fields={[{name:'credit_score',label:'诚信分',type:'number',min:0,max:100,value:item.credit_score,required:true}]} submit="保存诚信分" onSubmit={async values=>{await write(`/api/super/users/${item.id}/credit`,{credit_score:Number(values.credit_score)},'PUT');await ui.act(async()=>{},'诚信分已更新');ui.close()}}/></>}
function ReleaseForm({item={}}:{item?:Entity}){
  const ui=useUI();const base='/api/super/app-releases';const fields:Field[]=[
    ...(!item.id?[{name:'version_name',label:'版本名称',required:true},{name:'version_code',label:'版本号（正整数）',type:'number',min:1,required:true},{name:'apk',label:'APK 文件',type:'file',required:true}]:[]),
    {name:'title',label:'更新标题',value:item.title,required:true},{name:'changelog',label:'更新说明',type:'textarea',value:item.changelog,required:true},
    {name:'minimum_supported_version_code',label:'最低支持版本号',type:'number',min:1,required:true,value:item.minimum_supported_version_code||1}];
  async function action(name:string,method='POST'){if(await ui.act(()=>write(`${base}/${item.id}${name?`/${name}`:''}`,{},method),'版本状态已更新'))ui.close()}
  return <><p>{item.version_name} {item.status}</p><Form fields={fields} onSubmit={async(values,form)=>{if(item.id)await write(`${base}/${item.id}`,{title:values.title,changelog:values.changelog,minimum_supported_version_code:Number(values.minimum_supported_version_code)},'PATCH');else{form.set('delivery_mode','direct_package');form.set('platform','android');form.set('channel','stable');await write(base,form)}await ui.act(async()=>{},'版本草稿已保存');ui.close()}}/>{item.id&&<div className="form-actions">{item.status==='draft'&&<button className="btn primary" onClick={()=>ui.open('确认发布版本',<><p>发布 {item.version_name} 后，客户端将能检测并下载该版本。</p><button className="btn primary" onClick={()=>void action('publish')}>确认发布</button></>)}>发布版本</button>}{item.status==='published'&&<button className="btn" onClick={()=>ui.open('确认下架版本',<><p>确认下架 {item.version_name}？服务器会检查是否存在可用的回退版本。</p><button className="btn" onClick={()=>void action('withdraw')}>确认下架</button></>)}>下架版本</button>}{item.status==='draft'&&<button className="btn" onClick={()=>ui.open('删除版本草稿',<><p>确认删除草稿及其私有 APK 文件？</p><button className="btn danger" onClick={()=>void action('','DELETE')}>确认删除</button></>)}>删除草稿</button>}</div>}</>;
}
function Metrics({data}:{data:Entity}){return <><Stats items={[[data.requests||0,'近 7 天请求'],[`${((data.success_rate||0)*100).toFixed(1)}%`,'成功率'],[data.input_output_tokens||0,'输入输出 token'],[`${data.latency_ms?.p95||0} ms`,'P95 耗时']]}/><div className="panel table-scroll"><table className="data-table"><thead><tr><th>模型</th><th>请求</th><th>Token</th><th>已计价请求</th></tr></thead><tbody>{rows(data,'by_model').map(m=><tr key={m.name}><td>{m.name}</td><td>{m.requests}</td><td>{m.tokens}</td><td>{m.priced_requests}</td></tr>)}</tbody></table></div></>}
